/*
 * \brief  Types used within depot-autopilot
 * \author Norman Feske
 * \date   2025-11-12
 */

/*
 * Copyright (C) 2025 Genode Labs GmbH
 *
 * This file is part of the Genode OS framework, which is distributed
 * under the terms of the GNU Affero General Public License version 3.
 */

#ifndef _TYPES_H_
#define _TYPES_H_

#include <base/heap.h>
#include <children.h>

namespace Depot_autopilot {

	using namespace Depot_deploy;

	struct Clock
	{
		uint64_t ms;

		void print(Output &out) const
		{
			Genode::print(out, ms/1000, ".", (ms/100)%10, (ms/10)%10);
		}
	};

	struct Stats
	{
		unsigned failed, succeeded, skipped;

		Clock total_time;

		void print(Output &out) const
		{
			Genode::print(out, "succeeded: ", succeeded, " "
			                   "failed: ",    failed,    " "
			                   "skipped: ",   skipped);
		}
	};

	using Arch = String<16>;

	/**
	 * Utility to strip color escape sequences from output
	 *
	 * This utility merely considers sequences as generated by Genode's 'log',
	 * 'warning', or 'error' functions as typically used for the log output of
	 * components.
	 */
	struct Unescaped_output : Output
	{
		Output &_out;

		unsigned _skip = 0;

		Unescaped_output(Output &out) : _out(out) { }

		void out_char(char c) override
		{
			if (c == 27)
				_skip = 4; /* <esc>, '[', '0'..'9', 'm' */

			if (_skip) {
				_skip--;
				return;
			}

			_out.out_char(c);
		}
	};

	static inline size_t num_unescaped_bytes(auto &&... printable_args)
	{
		struct Counted : Output
		{
			size_t num_bytes = 0;
			void out_char(char) override { num_bytes++; }
		};

		Counted          counted { };
		Unescaped_output unescaped { counted };

		print(unescaped, printable_args...);

		return counted.num_bytes;
	}
}

#endif /* _TYPES_H_ */
