create_boot_directory

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/pkg/[drivers_interactive_pkg] \
                  [depot_user]/pkg/fonts_fs \
                  [depot_user]/src/init \
                  [depot_user]/src/dynamic_rom \
                  [depot_user]/src/report_rom \
                  [depot_user]/src/nitpicker \
                  [depot_user]/src/libc \
                  [depot_user]/src/libpng \
                  [depot_user]/src/zlib

install_config {
<config>
	<parent-provides>
		<service name="PD"/>
		<service name="CPU"/>
		<service name="ROM"/>
		<service name="RM"/>
		<service name="LOG"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
	</parent-provides>

	<default caps="100"/>

	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Timer"/></provides>
	</start>

	<start name="drivers" caps="1000">
		<resource name="RAM" quantum="32M" constrain_phys="yes"/>
		<binary name="init"/>
		<route>
			<service name="ROM" label="config"> <parent label="drivers.config"/> </service>
			<service name="Timer"> <child name="timer"/> </service>
			<any-service> <parent/> </any-service>
		</route>
		<provides>
			<service name="Input"/> <service name="Framebuffer"/>
		</provides>
	</start>

	<start name="nitpicker">
		<resource name="RAM" quantum="4M"/>
		<provides><service name="Nitpicker"/></provides>
		<config>
			<background color="#123456"/>
			<domain name="pointer" layer="1" content="client" label="no" origin="pointer" />
			<domain name="default" layer="3" content="client" label="no" hover="always" />

			<policy label_prefix="pointer" domain="pointer"/>
			<default-policy domain="default"/>
		</config>
	</start>

	<start name="pointer">
		<resource name="RAM" quantum="1M"/>
		<route>
			<service name="Nitpicker"> <child name="nitpicker" /> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

	<start name="dynamic_rom">
		<resource name="RAM" quantum="4M"/>
		<provides> <service name="ROM"/> </provides>
		<config verbose="yes">
			<rom name="dialog">
<inline description="step 0">
<dialog>
	<frame>
		<vbox>
			<hbox name="back">
				<float name="left" west="yes">
					<hbox>
						<button selected="yes" style="back" name="back">
							<hbox/>
						</button>
						<label name="label" font="title/regular" text=" Depot"/>
					</hbox>
				</float>
				<hbox name="right"/>
			</hbox>
			<hbox name="cnuke">
				<float name="left" west="yes">
					<hbox>
						<button style="radio" name="cnuke">
							<hbox/>
						</button>
						<label name="name" text=" cnuke ..."/>
					</hbox>
				</float>
				<hbox name="right"/>
			</hbox>
			<hbox name="nfeske">
				<float name="left" west="yes">
					<hbox>
						<button style="radio" name="nfeske">
							<hbox/>
						</button>
						<label name="name" text=" nfeske ..."/>
					</hbox>
				</float>
				<hbox name="right"/>
			</hbox>
			<hbox name="genodelabs">
				<float name="left" west="yes">
					<hbox>
						<button style="radio" name="genodelabs">
							<hbox/>
						</button>
						<label name="name" text=" genodelabs ..."/>
					</hbox>
				</float>
				<hbox name="right"/>
			</hbox>
			<hbox name="alex-ab">
				<float name="left" west="yes">
					<hbox>
						<button style="radio" name="alex-ab">
							<hbox/>
						</button>
						<label name="name" text=" alex-ab ..."/>
					</hbox>
				</float>
				<hbox name="right"/>
			</hbox>
			<hbox name="ehmry">
				<float name="left" west="yes">
					<hbox>
						<button style="radio" name="ehmry">
							<hbox/>
						</button>
						<label name="name" text=" ehmry ..."/>
					</hbox>
				</float>
				<hbox name="right"/>
			</hbox>
		</vbox>
	</frame>
</dialog>
</inline>
<sleep milliseconds="1000" />

<inline description="step 1">
<dialog>
	<frame>
		<vbox>
			<hbox name="back">
				<float name="left" west="yes">
					<hbox>
						<button selected="yes" style="back" name="back">
							<hbox/>
						</button>
						<label name="label" font="title/regular" text=" Depot"/>
					</hbox>
				</float>
				<hbox name="right"/>
			</hbox>
		</vbox>
	</frame>
</dialog>
</inline>
<sleep milliseconds="39" />
<inline description="step 5">
<dialog>
	<frame>
		<vbox>
			<hbox name="back">
				<float name="left" west="yes">
					<hbox>
						<button selected="yes" style="back" name="back">
							<hbox/>
						</button>
						<label name="label" font="title/regular" text=" Depot"/>
					</hbox>
				</float>
				<hbox name="right"/>
			</hbox>
			<hbox name="cnuke">
				<float name="left" west="yes">
					<hbox>
						<button style="radio" name="cnuke">
							<hbox/>
						</button>
						<label name="name" text=" cnuke ..."/>
					</hbox>
				</float>
				<hbox name="right"/>
			</hbox>
			<hbox name="nfeske">
				<float name="left" west="yes">
					<hbox>
						<button style="radio" name="nfeske">
							<hbox/>
						</button>
						<label name="name" text=" nfeske ..."/>
					</hbox>
				</float>
				<hbox name="right"/>
			</hbox>
			<hbox name="genodelabs">
				<float name="left" west="yes">
					<hbox>
						<button style="radio" name="genodelabs">
							<hbox/>
						</button>
						<label name="name" text=" genodelabs ..."/>
					</hbox>
				</float>
				<hbox name="right"/>
			</hbox>
			<hbox name="alex-ab">
				<float name="left" west="yes">
					<hbox>
						<button style="radio" name="alex-ab">
							<hbox/>
						</button>
						<label name="name" text=" alex-ab ..."/>
					</hbox>
				</float>
				<hbox name="right"/>
			</hbox>
			<hbox name="ehmry">
				<float name="left" west="yes">
					<hbox>
						<button style="radio" name="ehmry">
							<hbox/>
						</button>
						<label name="name" text=" ehmry ..."/>
					</hbox>
				</float>
				<hbox name="right"/>
			</hbox>
		</vbox>
	</frame>
</dialog>
</inline>
<sleep milliseconds="30000" />

			</rom>
		</config>
	</start>

	<start name="report_rom">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Report"/> <service name="ROM"/> </provides>
		<config verbose="yes"/>
	</start>

	<start name="fonts_fs" caps="300">
		<resource name="RAM" quantum="8M"/>
		<binary name="vfs"/>
		<route>
			<service name="ROM" label="config"> <parent label="fonts_fs.config"/> </service>
			<any-service> <parent/> </any-service>
		</route>
		<provides> <service name="File_system"/> </provides>
	</start>

	<start name="menu_view" caps="200">
		<resource name="RAM" quantum="8M"/>
		<config xpos="200" ypos="100">
			<report hover="yes"/>
			<libc stderr="/dev/log"/>
			<vfs>
				<tar name="menu_view_styles.tar" />
				<dir name="dev"> <log/> </dir>
				<dir name="fonts"> <fs label="fonts"/> </dir>
			</vfs>
		</config>
		<route>
			<service name="ROM" label="dialog"> <child name="dynamic_rom" /> </service>
			<service name="Report" label="hover"> <child name="report_rom"/> </service>
			<service name="File_system" label="fonts"> <child name="fonts_fs"/> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

</config>}

build { app/menu_view }

build_boot_image { menu_view menu_view_styles.tar }

run_genode_until forever
